export type Product = {
  id: string
  name: string
  desc: string
  price: number
  image: string
  category: "bolts" | "screws" | "anchors" | "tools"
  subcategory?: string
  material?: string
  size?: string
  inStock: boolean
  specifications: {
    dimensions?: string
    weight?: string
    threadPitch?: string
    headType?: string
    driveType?: string
    finish?: string
    strength?: string
    application?: string
    packageQuantity?: number
    warranty?: string
  }
  features: string[]
  images: string[]
}

export const products: Product[] = [
  // Bolts
  {
    id: "b1",
    name: "Heavy-Duty Hex Bolts",
    desc: "Zinc-plated, corrosion-resistant, ideal for structural builds.",
    price: 7.99,
    image: "/products/hex-bolts.jpg",
    category: "bolts",
    subcategory: "hex-bolts",
    material: "steel",
    size: "M8-M20",
    inStock: true,
    specifications: {
      dimensions: "M8 x 25mm to M20 x 100mm",
      weight: "0.5kg per pack",
      threadPitch: "Standard metric thread",
      headType: "Hexagonal",
      finish: "Zinc plated",
      strength: "Grade 8.8",
      application: "Structural, mechanical",
      packageQuantity: 25,
      warranty: "1 year against defects",
    },
    features: [
      "Corrosion resistant zinc plating",
      "High tensile strength Grade 8.8",
      "Precision machined threads",
      "Suitable for outdoor use",
      "Multiple sizes available",
    ],
    images: ["/products/hex-bolts.jpg", "/products/hex-bolts-2.png", "/products/hex-bolts-3.png"],
  },
  {
    id: "b2",
    name: "Carriage Bolts Set",
    desc: "Smooth rounded head bolts with square neck. 50 pieces.",
    price: 15.5,
    image: "/products/carriage-bolts.png",
    category: "bolts",
    subcategory: "carriage-bolts",
    material: "steel",
    size: "M6-M12",
    inStock: true,
    specifications: {
      dimensions: "M6 x 30mm to M12 x 80mm",
      weight: "1.2kg per pack",
      headType: "Round head with square neck",
      finish: "Black oxide",
      strength: "Grade 4.6",
      application: "Wood construction, furniture",
      packageQuantity: 50,
      warranty: "6 months",
    },
    features: [
      "Smooth rounded head design",
      "Square neck prevents rotation",
      "Ideal for wood applications",
      "Black oxide finish",
      "Bulk pack of 50 pieces",
    ],
    images: ["/products/carriage-bolts.png", "/products/carriage-bolts-2.png"],
  },
  {
    id: "b3",
    name: "Eye Bolts",
    desc: "Forged eye bolts for lifting and rigging applications.",
    price: 12.3,
    image: "/products/eye-bolts.png",
    category: "bolts",
    subcategory: "eye-bolts",
    material: "stainless-steel",
    size: "M8-M16",
    inStock: true,
    specifications: {
      dimensions: "M8 x 40mm to M16 x 80mm",
      weight: "0.8kg per pack",
      headType: "Forged eye",
      finish: "Stainless steel 316",
      strength: "Working load limit 500kg-2000kg",
      application: "Lifting, rigging, marine",
      packageQuantity: 10,
      warranty: "2 years",
    },
    features: [
      "Marine grade stainless steel",
      "Forged construction for strength",
      "Suitable for lifting applications",
      "Corrosion resistant",
      "Load tested and certified",
    ],
    images: ["/products/eye-bolts.png", "/products/eye-bolts-2.png"],
  },
  {
    id: "b4",
    name: "U-Bolts",
    desc: "Threaded U-shaped bolts for pipe and rod mounting.",
    price: 9.75,
    image: "/products/u-bolts.png",
    category: "bolts",
    subcategory: "u-bolts",
    material: "galvanized",
    size: "Various",
    inStock: false,
    specifications: {
      dimensions: "25mm to 100mm pipe diameter",
      weight: "1.5kg per pack",
      threadPitch: "M8 and M10 thread",
      finish: "Hot-dip galvanized",
      strength: "Grade 4.6",
      application: "Pipe mounting, exhaust systems",
      packageQuantity: 20,
      warranty: "1 year",
    },
    features: [
      "Hot-dip galvanized coating",
      "Various pipe diameters",
      "Includes nuts and washers",
      "Heavy-duty construction",
      "Suitable for outdoor use",
    ],
    images: ["/products/u-bolts.png"],
  },

  // Screws
  {
    id: "s1",
    name: "Stainless Steel Screws Set",
    desc: "Assorted sizes with Phillips heads. 500 pcs.",
    price: 19.99,
    image: "/products/stainless-screws.jpg",
    category: "screws",
    subcategory: "wood-screws",
    material: "stainless-steel",
    size: "Mixed",
    inStock: true,
    specifications: {
      dimensions: '#6 x 1" to #12 x 3"',
      weight: "2.5kg per pack",
      driveType: "Phillips head",
      headType: "Countersunk",
      finish: "Stainless steel 304",
      strength: "High tensile",
      application: "Wood, composite materials",
      packageQuantity: 500,
      warranty: "Lifetime against corrosion",
    },
    features: [
      "Corrosion resistant stainless steel",
      "Sharp self-drilling point",
      "Deep Phillips drive",
      "Countersunk head design",
      "Assorted sizes in convenient pack",
    ],
    images: ["/products/stainless-screws.jpg", "/products/stainless-screws-2.png"],
  },
  {
    id: "s2",
    name: "Self-Tapping Screws",
    desc: "Sharp point screws for metal and plastic. 100 pieces.",
    price: 8.45,
    image: "/products/self-tapping-screws.png",
    category: "screws",
    subcategory: "self-tapping",
    material: "steel",
    size: "#6-#12",
    inStock: true,
    specifications: {
      dimensions: '#6 x 1/2" to #12 x 2"',
      weight: "0.8kg per pack",
      driveType: "Phillips and hex",
      headType: "Pan head",
      finish: "Zinc plated",
      strength: "Hardened steel",
      application: "Sheet metal, plastic",
      packageQuantity: 100,
      warranty: "6 months",
    },
    features: [
      "Self-drilling sharp point",
      "Hardened steel construction",
      "Dual drive options",
      "Zinc plated finish",
      "Ideal for thin materials",
    ],
    images: ["/products/self-tapping-screws.png"],
  },
  {
    id: "s3",
    name: "Machine Screws",
    desc: "Precision threaded screws for mechanical assemblies.",
    price: 11.2,
    image: "/products/machine-screws.png",
    category: "screws",
    subcategory: "machine-screws",
    material: "steel",
    size: "M3-M8",
    inStock: true,
    specifications: {
      dimensions: "M3 x 10mm to M8 x 50mm",
      weight: "1.0kg per pack",
      threadPitch: "Standard metric fine thread",
      driveType: "Hex socket",
      headType: "Socket head cap",
      finish: "Black oxide",
      strength: "Grade 12.9",
      application: "Machinery, electronics",
      packageQuantity: 200,
      warranty: "1 year",
    },
    features: [
      "Precision machined threads",
      "High strength Grade 12.9",
      "Socket head design",
      "Black oxide finish",
      "Metric sizing",
    ],
    images: ["/products/machine-screws.png"],
  },
  {
    id: "s4",
    name: "Drywall Screws",
    desc: "Black phosphate coated screws for drywall installation.",
    price: 6.8,
    image: "/products/drywall-screws.png",
    category: "screws",
    subcategory: "drywall",
    material: "steel",
    size: "25mm-50mm",
    inStock: true,
    specifications: {
      dimensions: "25mm, 32mm, 41mm, 50mm lengths",
      weight: "1.8kg per pack",
      driveType: "Phillips #2",
      headType: "Bugle head",
      finish: "Black phosphate",
      strength: "Hardened steel",
      application: "Drywall to wood/metal studs",
      packageQuantity: 1000,
      warranty: "6 months",
    },
    features: [
      "Sharp self-drilling point",
      "Bugle head design",
      "Black phosphate coating",
      "Deep Phillips drive",
      "Bulk contractor pack",
    ],
    images: ["/products/drywall-screws.png"],
  },

  // Anchors
  {
    id: "a1",
    name: "Masonry Anchors",
    desc: "High-hold anchors for brick and concrete installations.",
    price: 12.49,
    image: "/products/masonry-anchors.jpg",
    category: "anchors",
    subcategory: "masonry",
    material: "nylon",
    size: "6mm-12mm",
    inStock: true,
    specifications: {
      dimensions: "6mm, 8mm, 10mm, 12mm diameter",
      weight: "0.5kg per pack",
      finish: "Natural nylon",
      strength: "Pull-out force 800-2500N",
      application: "Brick, concrete, stone",
      packageQuantity: 100,
      warranty: "2 years",
    },
    features: [
      "High-quality nylon construction",
      "Expansion design for secure hold",
      "Suitable for solid masonry",
      "Color-coded by size",
      "Includes matching screws",
    ],
    images: ["/products/masonry-anchors.jpg", "/products/masonry-anchors-2.png"],
  },
  {
    id: "a2",
    name: "Toggle Bolts",
    desc: "Spring-loaded toggle bolts for hollow wall mounting.",
    price: 14.75,
    image: "/products/toggle-bolts.png",
    category: "anchors",
    subcategory: "toggle",
    material: "steel",
    size: "M6-M10",
    inStock: true,
    specifications: {
      dimensions: "M6 x 50mm to M10 x 75mm",
      weight: "1.2kg per pack",
      headType: "Spring-loaded toggle",
      finish: "Zinc plated",
      strength: "Hold capacity 50-150kg",
      application: "Hollow walls, plasterboard",
      packageQuantity: 25,
      warranty: "1 year",
    },
    features: [
      "Spring-loaded toggle mechanism",
      "High load capacity",
      "Zinc plated finish",
      "Easy installation",
      "Suitable for hollow walls",
    ],
    images: ["/products/toggle-bolts.png"],
  },
  {
    id: "a3",
    name: "Expansion Anchors",
    desc: "Heavy-duty expansion anchors for concrete applications.",
    price: 18.9,
    image: "/products/expansion-anchors.png",
    category: "anchors",
    subcategory: "expansion",
    material: "steel",
    size: "M8-M16",
    inStock: true,
    specifications: {
      dimensions: "M8 x 60mm to M16 x 120mm",
      weight: "2.0kg per pack",
      finish: "Galvanized steel",
      strength: "Tensile load 5-25kN",
      application: "Concrete, masonry",
      packageQuantity: 20,
      warranty: "5 years",
    },
    features: [
      "Heavy-duty expansion design",
      "Galvanized steel construction",
      "High tensile strength",
      "Professional grade",
      "Suitable for structural applications",
    ],
    images: ["/products/expansion-anchors.png"],
  },
  {
    id: "a4",
    name: "Plastic Wall Plugs",
    desc: "Universal wall plugs for lightweight applications.",
    price: 4.25,
    image: "/products/wall-plugs.png",
    category: "anchors",
    subcategory: "wall-plugs",
    material: "nylon",
    size: "5mm-10mm",
    inStock: true,
    specifications: {
      dimensions: "5mm, 6mm, 8mm, 10mm diameter",
      weight: "0.3kg per pack",
      finish: "Natural nylon",
      strength: "Pull-out force 200-800N",
      application: "Brick, concrete, block",
      packageQuantity: 200,
      warranty: "1 year",
    },
    features: [
      "Universal design",
      "Color-coded sizes",
      "Easy installation",
      "Suitable for most wall types",
      "Bulk economy pack",
    ],
    images: ["/products/wall-plugs.png"],
  },

  // Tools
  {
    id: "t1",
    name: "Adjustable Wrench Pro",
    desc: "Hardened steel with comfort grip and precise scale.",
    price: 24.0,
    image: "/products/adjustable-wrench.jpg",
    category: "tools",
    subcategory: "wrenches",
    material: "steel",
    size: "250mm",
    inStock: true,
    specifications: {
      dimensions: "250mm length",
      weight: "0.4kg",
      finish: "Chrome plated",
      strength: "Hardened steel jaws",
      application: "General maintenance",
      warranty: "Lifetime warranty",
    },
    features: [
      "Hardened steel construction",
      "Comfort grip handle",
      "Precise jaw adjustment",
      "Chrome plated finish",
      "Laser-etched scale",
    ],
    images: ["/products/adjustable-wrench.jpg", "/products/adjustable-wrench-2.png"],
  },
  {
    id: "t2",
    name: "Socket Set",
    desc: "Complete 42-piece socket set with ratchet handle.",
    price: 45.6,
    image: "/products/socket-set.png",
    category: "tools",
    subcategory: "sockets",
    material: "chrome-vanadium",
    size: "8mm-24mm",
    inStock: true,
    specifications: {
      dimensions: "8mm to 24mm sockets",
      weight: "2.5kg",
      finish: "Chrome vanadium steel",
      strength: "Professional grade",
      application: "Automotive, mechanical",
      packageQuantity: 42,
      warranty: "Lifetime warranty",
    },
    features: [
      "Chrome vanadium steel",
      "72-tooth ratchet mechanism",
      "Quick-release mechanism",
      "Blow-molded case",
      "Professional quality",
    ],
    images: ["/products/socket-set.png", "/products/socket-set-2.png"],
  },
  {
    id: "t3",
    name: "Screwdriver Set",
    desc: "Magnetic tip screwdrivers with ergonomic handles.",
    price: 16.3,
    image: "/products/screwdriver-set.png",
    category: "tools",
    subcategory: "screwdrivers",
    material: "steel",
    size: "Various",
    inStock: true,
    specifications: {
      dimensions: "Various lengths 75mm-200mm",
      weight: "0.8kg",
      driveType: "Phillips and flathead",
      finish: "Chrome vanadium tips",
      strength: "Hardened tips",
      application: "General purpose",
      packageQuantity: 8,
      warranty: "2 years",
    },
    features: ["Magnetic tips", "Ergonomic handles", "Chrome vanadium steel", "Non-slip grip", "Storage rack included"],
    images: ["/products/screwdriver-set.png"],
  },
  {
    id: "t4",
    name: "Drill Bit Set",
    desc: "HSS drill bits for metal, wood, and plastic. 25 pieces.",
    price: 22.85,
    image: "/products/drill-bits.png",
    category: "tools",
    subcategory: "drill-bits",
    material: "hss",
    size: "1mm-13mm",
    inStock: false,
    specifications: {
      dimensions: "1mm to 13mm diameter",
      weight: "0.6kg",
      finish: "High-speed steel",
      strength: "HSS construction",
      application: "Metal, wood, plastic",
      packageQuantity: 25,
      warranty: "1 year",
    },
    features: [
      "High-speed steel construction",
      "135° split point design",
      "Suitable for multiple materials",
      "Metal storage case",
      "Professional quality",
    ],
    images: ["/products/drill-bits.png"],
  },
]

export function getProductsByCategory(category: string) {
  return products.filter((product) => product.category === category)
}

export function getUniqueSubcategories(category: string) {
  const categoryProducts = getProductsByCategory(category)
  return [...new Set(categoryProducts.map((p) => p.subcategory).filter(Boolean))]
}

export function getUniqueMaterials(category: string) {
  const categoryProducts = getProductsByCategory(category)
  return [...new Set(categoryProducts.map((p) => p.material).filter(Boolean))]
}

export function getRelatedProducts(productId: string, category: string, limit = 4) {
  return products.filter((product) => product.id !== productId && product.category === category).slice(0, limit)
}

export function getProductById(id: string) {
  return products.find((product) => product.id === id)
}
